### ISSUE TITLE
[Feature Request] Add support for overriding show parameters

### ISSUE THREAD

**Issue by ahmubashshir** [iamkroot/trakt-scrobbler#95]
If possible, implement something like `XDG_DATA_HOME/trakt-scrobbler/trakt_cache.json` for overriding show parameters.

Syntax can be like
```yaml
Beatless-Final-Stage:
  episodes-start: 21 # Remap Beatless-Final-Stage-S01E01... to Beatless-S01E21...
  id: 124828
  type: show
"Nisekoi\ua789":  # Remap Nisekoi: to Nisekoi S02
  season: 2
  id: 74233
  type: show
```

We should use toml/yaml as it is cumbersome to read/modify json manually.

**Comment by iamkroot** [comment]
This feels like it might get really cumbersome, really fast. Sure, we might add support for the scenarios you're asking for, but then someone else will come along and ask for more powerful remapping. 

The following things need to be kept in mid:
- Match not just on name, but arbitrary parameters (name, season, media type)
- Match with logical operators (eg: match if (name == "x" and season == 3) or name == "y"). Granted this seems like a very pedantic requirement
- The `episodes-start` would have to be something like `episodes-delta`, since we consider each file individually, not as a part of a folder. 
- User may not know the trakt id of the target
- Many other variations in the target specification

I can't come up with a clean syntax for this right now.

Why not just rename the files temporarily while watching the show?

**Comment by JourneyOver** [comment]
@iamkroot TBH I would love something like this as well, as I've run into two instances so far where it would either not scrobble a show or scrobble the wrong movie due to it either not being able to find the trakt ID or it pulling in the completely wrong trakt ID.

My two examples of it not finding the trakt ID or it pulling in the wrong trakt ID are:

The new [Mulan](https://trakt.tv/movies/mulan-2020) movie, it instead seems to see it as the [animated](https://trakt.tv/movies/mulan-1998) version and pulls in the trakt ID as such. 

The Hardy Boys, on plex it's named as `The Hardy Boys (2020)` but doing a search on trakt as that does not provide a search result, instead you'd have to search it as just `The Hardy Boys` on trakt to get a result. Doing so though provides results for all the other `The Hardy Boys` tv shows as well which would probably result in the same issue with Mulan. Not all TV Shows have this issue, as for example the 2016 tv show of `MacGyver` you can search for both `MacGyver (2016)` and `MacGyver` and get the result that you need (though the later provides the results of the other `MacGyver` tv shows and movies as well.

So it would honestly be nice to be able to override at least the trakt ID possibly.

**Comment by iamkroot** [comment]
@JourneyOver Regarding the years thing, that issue is specific to Plex actually. For other media players, we use [guessit](https://github.com/guessit-io/guessit/) on the file path, and since it uses regexes under the hood, it picks up the year if present in the name. Using that, the scrobbler actually does specify the year when doing a trakt search, so your files would scrobble correctly. But for Plex, the year is a part of the media title, and we're not doing anything fancy to detect/extract years. Maybe this feature request can be moved to it's own issue.

**Comment by iamkroot** [comment]
Just adding this here so it's all in one place. There should be a CLI command to do the Trakt ID lookup so that users can find it easily. I'm thinking something like `trakts lookup --type=[show|movie] "TITLE" --year YEAR`. The results also need to be pretty-printed:
* Limit to top 3 results
* Printed fields: Media title, year, description, and of course, the trakt id
* We can provide a `--brief` flag that prints only the Trakt ID of the top result
* Similarly, a `--verbose` flag would print more fields (Director, Airdate, etc.)

Implementing this should be pretty simple, since it's just a wrapper over the [`search`](https://github.com/iamkroot/trakt-scrobbler/blob/781cd66a21c495f97d5db7208be9e0b93469ed9f/trakt_scrobbler/trakt_interface.py#L14) function.

**Comment by ahmubashshir** [comment]
btw... instead of trakt id, we can use trakt short name like:
```yaml
Beatless-Final-Stage:
  episodes-start: 21 # Remap Beatless-Final-Stage-S01E01... to Beatless-S01E21...
  slug: beatless # from https://trakt.tv/shows/beatless
  type: show
"Nisekoi\ua789":  # Remap Nisekoi: to Nisekoi S02
  season: 2
  slug: nisekoi # from https://trakt.tv/shows/nisekoi
  type: show
```

**Comment by iamkroot** [comment]
Yeah when working on the BacklogCleaner [rewrite](https://github.com/iamkroot/trakt-scrobbler/tree/new_backlog), I realized that fetching the Trakt ID is actually completely unnecessary. Just sending the title (even without slugification) works while scrobbling (it automatically picks the first item from search results, which is exactly what we do). 

But I think keeping the Trakt IDs around is a good idea, especially in cases like yours when we want to accurately specify the media. I think I saw some other scrobbler which uses the Django's `slugify` util to convert the media title into a slug, and send that as the identifier. But that is prone to errors. Will need to think about how we can allow _either_ the Trakt ID _or_ the slug for specifying the media. 

This could be a separate issue too, since it's mostly orthogonal to the "overriding" scenario.

**Comment by iamkroot** [comment]
So, I started watching the [Monogatari](https://trakt.tv/shows/monogatari) series and the [_absolute_ clusterfuck](https://trakt.tv/users/agent531c/lists/monogatari-watchlist) that is its episode ordering led me to finally implement this feature.
@ahmubashshir when you get some time, please do give it a test-
Install from branch:
1. Stop the scrobbler with `trakts stop`
2. Run `pipx install --force --pip-args='--force-reinstall' git+https://github.com/iamkroot/trakt-scrobbler.git@mediainfo-remap`
3. Start scrobbler with `trakts start`

You'll need to create a new file called `remap_rules.toml` alongside the current config path (`$HOME/.config/trakt-scrobbler/`). Here's the current (WIP) schema along with a few sample rules:

```toml
# Sample trakt scrobbler remap file.

# schema:
# there should be a toplevel key "rules", which is a list of the following-
# [match]
#   - one or more of path, title, season, episode, year
#   - path should be valid a Python regex pattern
#     - you can also capture substrings using "(?P<name>pattern)" syntax. These will override the default-extracted values from guessit.
#   - season, episode, year support ranges.
#       - For instance, 'season: "1:3,5"' will match any season in {1,2,3,5}
#   - if needed, we can add a "fuzzy-title" in the future to do edit-distance based matching
#   - specifying multiple fields means all of them should match.
# [type]
#   - one of "episode" or "movie"
# [id]
#   - one of trakt_slug, trakt_id, or title (to select top result)
#   - can use placeholders for extracted values like "{episode}", "{title}", "{year}", etc.
#      - the placeholder names should match the extracted guessit keys or regex capture group names
#   - "title" can contain an optional year inside parentheses. Eg: "The Man from Earth (2007)"
# [season]
#   - optional. If not provided, the extracted value from path/regex will be used.
#   - any number starting from 0
#   - 0 corresponds to "Specials" season on Trakt
# [episode_delta]
#   - optional. Default is 0
#   - any integer (positive or negative)
#   - will be added to the episode number extracted from path/regex


# for this sample, the match paths correspond to the Monogatari torrent v2 from DB encodes.

[[rules]]
match.path = ".*/01 Bakemonogatari/.*"
match.episode = "1:12"

id.trakt_slug = "monogatari"
type = "episode"

season = 1

[[rules]]
match.path = ".*/01 Bakemonogatari/.*"
match.episode = "13:15"

id.trakt_slug = "monogatari"
type = "episode"

season = 0
episode_delta = -11

[[rules]]
match.path = ".*/Kizumonogatari/.*"
id.title = "Kizumonogatari Part {episode}"
type = "movie"

[[rules]]
match.path = ".*/02 Nisemonogatari/.*"

id.trakt_slug = "monogatari"
type = "episode"

season = 2

[[rules]]
match.path = ".*/03 Nekomonogatari (Kuro)/.*"

id.trakt_slug = "monogatari"
type = "episode"

season = 0
episode_delta = 5

[[rules]]
match.path = ".*/Arc 01 Nekomonogatari Shiro/.*"

id.trakt_slug = "monogatari"
type = "episode"

season = 3

[[rules]]
match.path = ".*/Arc 02 Kabukimonogatari/.*"

id.trakt_slug = "monogatari"
type = "episode"

season = 3
episode_delta = 5

[[rules]]
match.path = ".*/Arc 06 Hanamonogatari/.*"

id.trakt_slug = "monogatari"
type = "episode"

season = 0
episode_delta = 12

[[rules]]
match.path = ".*/Arc 03 Otorimonogatari/.*"

id.trakt_slug = "monogatari"
type = "episode"

season = 3
episode_delta = 9

[[rules]]
match.path = ".*/Arc 04 Onimonogatari/.*"

id.trakt_slug = "monogatari"
type = "episode"

season = 3
episode_delta = 13

[[rules]]
match.path = ".*/Arc 05 Koimonogatari/.*"

id.trakt_slug = "monogatari"
type = "episode"

season = 3
episode_delta = 17

[[rules]]
match.path = ".*/01 Tsukimonogatari/.*"

id.trakt_slug = "monogatari"
type = "episode"

season = 0
episode_delta = 17

[[rules]]
match.path = ".*/03 Koyomimonogatari/.*"

id.trakt_slug = "monogatari"
type = "episode"

season = 0
episode_delta = 21

[[rules]]
match.path = ".*/02 Owarimonogatari/.*"

id.trakt_slug = "monogatari"
type = "episode"

season = 4

[[rules]]
match.path = ".*/04 Owarimonogatari Second Season/.*"

id.trakt_slug = "monogatari"
type = "episode"

season = 0
episode_delta = 34

[[rules]]
match.path = ".*/05 Zoku Owarimonogatari/.*"

id.trakt_slug = "monogatari"
type = "episode"

season = 0
episode_delta = 41

```

Lemme know what you think!
